// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeMAjYptAGtWa1HcxtQU903bfP9vxPAQg',
    appId: '1:28581649234:web:d7be9c6326fbb1345a788b',
    messagingSenderId: '28581649234',
    projectId: 'plantpal-196e9',
    authDomain: 'plantpal-196e9.firebaseapp.com',
    databaseURL: 'https://plantpal-196e9-default-rtdb.firebaseio.com',
    storageBucket: 'plantpal-196e9.appspot.com',
    measurementId: 'G-8JJ76BTBES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWMotfF_4FOql2-XFQsQAagYimlKF0eTc',
    appId: '1:28581649234:android:6db790b6eeb8f23a5a788b',
    messagingSenderId: '28581649234',
    projectId: 'plantpal-196e9',
    databaseURL: 'https://plantpal-196e9-default-rtdb.firebaseio.com',
    storageBucket: 'plantpal-196e9.appspot.com',
  );
}
